// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto-encoding/simple-message/simple-message.proto

package simple_message

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Test1 struct {
	A                    *int32   `protobuf:"varint,1,opt,name=a" json:"a,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test1) Reset()         { *m = Test1{} }
func (m *Test1) String() string { return proto.CompactTextString(m) }
func (*Test1) ProtoMessage()    {}
func (*Test1) Descriptor() ([]byte, []int) {
	return fileDescriptor_34ec177e2f5853e3, []int{0}
}

func (m *Test1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test1.Unmarshal(m, b)
}
func (m *Test1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test1.Marshal(b, m, deterministic)
}
func (m *Test1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test1.Merge(m, src)
}
func (m *Test1) XXX_Size() int {
	return xxx_messageInfo_Test1.Size(m)
}
func (m *Test1) XXX_DiscardUnknown() {
	xxx_messageInfo_Test1.DiscardUnknown(m)
}

var xxx_messageInfo_Test1 proto.InternalMessageInfo

func (m *Test1) GetA() int32 {
	if m != nil && m.A != nil {
		return *m.A
	}
	return 0
}

type Test2 struct {
	B                    *int64   `protobuf:"varint,1,opt,name=b" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Test2) Reset()         { *m = Test2{} }
func (m *Test2) String() string { return proto.CompactTextString(m) }
func (*Test2) ProtoMessage()    {}
func (*Test2) Descriptor() ([]byte, []int) {
	return fileDescriptor_34ec177e2f5853e3, []int{1}
}

func (m *Test2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Test2.Unmarshal(m, b)
}
func (m *Test2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Test2.Marshal(b, m, deterministic)
}
func (m *Test2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Test2.Merge(m, src)
}
func (m *Test2) XXX_Size() int {
	return xxx_messageInfo_Test2.Size(m)
}
func (m *Test2) XXX_DiscardUnknown() {
	xxx_messageInfo_Test2.DiscardUnknown(m)
}

var xxx_messageInfo_Test2 proto.InternalMessageInfo

func (m *Test2) GetB() int64 {
	if m != nil && m.B != nil {
		return *m.B
	}
	return 0
}

func init() {
	proto.RegisterType((*Test1)(nil), "Test1")
	proto.RegisterType((*Test2)(nil), "Test2")
}

func init() {
	proto.RegisterFile("proto-encoding/simple-message/simple-message.proto", fileDescriptor_34ec177e2f5853e3)
}

var fileDescriptor_34ec177e2f5853e3 = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x32, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4d, 0xcd, 0x4b, 0xce, 0x4f, 0xc9, 0xcc, 0x4b, 0xd7, 0x2f, 0xce, 0xcc, 0x2d, 0xc8,
	0x49, 0xd5, 0xcd, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x45, 0xe3, 0xea, 0x81, 0x15, 0x2b, 0x89,
	0x72, 0xb1, 0x86, 0xa4, 0x16, 0x97, 0x18, 0x0a, 0xf1, 0x70, 0x31, 0x26, 0x4a, 0x30, 0x2a, 0x30,
	0x6a, 0xb0, 0x06, 0x31, 0x26, 0xc2, 0x84, 0x8d, 0x40, 0xc2, 0x49, 0x60, 0x61, 0xe6, 0x20, 0xc6,
	0x24, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0xef, 0xb4, 0x7c, 0xaf, 0x62, 0x00, 0x00, 0x00,
}
